version: "3"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
      MYSQL_TCP_PORT: 3307
    ports:
        - 8080:8080
        - 3307:3307
  neo:
    image: neo4j:4.4.6-community
    ports:
        - 7474:7474
        - 7687:7687
    restart: always
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./neo4j/data:/data
  notebook:
    build: notebook/
    ports:
      - 8888:8888
    volumes:
       - ./:/home/jovyan/work/data
    environment:
      - GRANT_SUDO=yes